#!/usr/bin/env node
/**
 * i18n translation pipeline for 3DStreet (#656).
 *
 * Source of truth: src/editor/i18n/locales/en.json (generated by
 * `npm run i18n:extract`, formatjs shape: { id: { defaultMessage, ... } }).
 *
 * For each target locale this script:
 *   - finds keys that are missing or whose English source changed since the
 *     last translation (tracked in .translation-manifest.json),
 *   - removes orphaned keys no longer present in en.json,
 *   - translates the stale keys with an LLM (Anthropic Messages API),
 *   - writes a flat { id: "translated string" } catalog.
 *
 * Modes:
 *   node scripts/i18n/translate.mjs            translate stale keys (needs ANTHROPIC_API_KEY)
 *   node scripts/i18n/translate.mjs --check    report drift only, exit 1 if any (CI)
 *   node scripts/i18n/translate.mjs --locale es,pt-BR   restrict to given locales
 *
 * Env:
 *   ANTHROPIC_API_KEY   required for translation (not for --check)
 *   I18N_MODEL          model id (default: claude-sonnet-4-6)
 *   ANTHROPIC_BASE_URL  optional API base override
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const LOCALES_DIR = join(__dirname, '../../src/editor/i18n/locales');
const EN_PATH = join(LOCALES_DIR, 'en.json');
const MANIFEST_PATH = join(LOCALES_DIR, '.translation-manifest.json');

const TARGET_LOCALES = {
  es: 'Spanish (Latin American / neutral, suitable for Mexico, Spain, and South America)',
  'pt-BR': 'Brazilian Portuguese'
};

// Domain glossary so the LLM keeps urban-planning / street-design terminology
// consistent and on-target. Extend as new terms appear.
const GLOSSARY = `
Domain: 3DStreet is a browser-based urban planning / street design tool.
Keep these UI/domain terms natural and consistent:
- "street", "lane", "sidewalk", "bike lane", "drive lane", "segment", "intersection",
  "crosswalk", "median", "parking", "transit", "scene", "layer", "entity", "mixin",
  "viewer mode", "editor", "undo", "redo".
- Keep product names untranslated: 3DStreet, Streetmix, StreetPlan, Google 3D Tiles, A-Frame, PostHog.
`;

const args = process.argv.slice(2);
const CHECK_ONLY = args.includes('--check');
const localeArgIdx = args.indexOf('--locale');
const localeFilter =
  localeArgIdx !== -1 && args[localeArgIdx + 1]
    ? args[localeArgIdx + 1].split(',').map((s) => s.trim())
    : null;

const MODEL = process.env.I18N_MODEL || 'claude-sonnet-4-6';
const API_BASE = process.env.ANTHROPIC_BASE_URL || 'https://api.anthropic.com';
const BATCH_SIZE = 40;

function readJson(path, fallback) {
  if (!existsSync(path)) return fallback;
  return JSON.parse(readFileSync(path, 'utf8'));
}

function writeJsonSorted(path, obj) {
  const sorted = Object.keys(obj)
    .sort()
    .reduce((acc, k) => ((acc[k] = obj[k]), acc), {});
  writeFileSync(path, JSON.stringify(sorted, null, 2) + '\n');
}

/** Flatten formatjs en.json { id: { defaultMessage } } -> { id: string }. */
function flattenEn(en) {
  const out = {};
  for (const [id, descriptor] of Object.entries(en)) {
    out[id] =
      typeof descriptor === 'string' ? descriptor : descriptor.defaultMessage;
  }
  return out;
}

function computeDelta(enFlat, existing, manifestForLocale) {
  const toTranslate = [];
  for (const [id, source] of Object.entries(enFlat)) {
    const hasTranslation = Object.prototype.hasOwnProperty.call(existing, id);
    const sourceChanged = manifestForLocale[id] !== source;
    if (!hasTranslation || sourceChanged) toTranslate.push(id);
  }
  const orphans = Object.keys(existing).filter(
    (id) => !Object.prototype.hasOwnProperty.call(enFlat, id)
  );
  return { toTranslate, orphans };
}

async function translateBatch(entries, localeName) {
  const payload = entries.reduce((acc, [id, text]) => ((acc[id] = text), acc), {});
  const system =
    `You are a professional software localizer translating UI strings to ${localeName}.\n` +
    GLOSSARY +
    `\nRules:\n` +
    `- Translate the VALUE of each key. Keep the KEY (id) unchanged.\n` +
    `- Preserve ICU/interpolation placeholders EXACTLY, e.g. {count}, {name}, <b>...</b>. Do not translate text inside { }.\n` +
    `- Preserve leading/trailing whitespace and punctuation. Match capitalization style.\n` +
    `- Keep it concise and natural for a UI button/label/tooltip context.\n` +
    `- Return ONLY a JSON object mapping each id to its translation. No prose, no code fences.`;

  const res = await fetch(`${API_BASE}/v1/messages`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': process.env.ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 8192,
      system,
      messages: [
        {
          role: 'user',
          content: `Translate these UI strings to ${localeName}:\n\n${JSON.stringify(payload, null, 2)}`
        }
      ]
    })
  });

  if (!res.ok) {
    throw new Error(`Anthropic API error ${res.status}: ${await res.text()}`);
  }
  const data = await res.json();
  const textBlock = data.content?.find((b) => b.type === 'text')?.text ?? '';
  const jsonText = textBlock.replace(/^```(?:json)?\s*|\s*```$/g, '').trim();
  return JSON.parse(jsonText);
}

async function main() {
  const en = readJson(EN_PATH, null);
  if (!en) {
    console.error(`Missing ${EN_PATH}. Run "npm run i18n:extract" first.`);
    process.exit(1);
  }
  const enFlat = flattenEn(en);
  const manifest = readJson(MANIFEST_PATH, {});
  const locales = Object.keys(TARGET_LOCALES).filter(
    (l) => !localeFilter || localeFilter.includes(l)
  );

  let drift = false;

  for (const locale of locales) {
    const localePath = join(LOCALES_DIR, `${locale}.json`);
    const existing = readJson(localePath, {});
    const manifestForLocale = manifest[locale] || {};
    const { toTranslate, orphans } = computeDelta(
      enFlat,
      existing,
      manifestForLocale
    );

    if (CHECK_ONLY) {
      if (toTranslate.length || orphans.length) {
        drift = true;
        console.error(
          `[${locale}] DRIFT: ${toTranslate.length} key(s) need translation, ` +
            `${orphans.length} orphan(s) to remove.`
        );
        if (toTranslate.length) {
          console.error(`  needs translation: ${toTranslate.slice(0, 20).join(', ')}` +
            (toTranslate.length > 20 ? ` … (+${toTranslate.length - 20})` : ''));
        }
      } else {
        console.log(`[${locale}] up to date (${Object.keys(existing).length} keys).`);
      }
      continue;
    }

    // Prune orphans.
    for (const id of orphans) {
      delete existing[id];
      delete manifestForLocale[id];
    }

    if (!toTranslate.length) {
      console.log(`[${locale}] up to date — nothing to translate.`);
      writeJsonSorted(localePath, existing);
      manifest[locale] = manifestForLocale;
      continue;
    }

    if (!process.env.ANTHROPIC_API_KEY) {
      console.error(
        `[${locale}] ${toTranslate.length} key(s) need translation but ANTHROPIC_API_KEY is not set.`
      );
      process.exit(1);
    }

    console.log(
      `[${locale}] translating ${toTranslate.length} key(s) with ${MODEL}…`
    );
    for (let i = 0; i < toTranslate.length; i += BATCH_SIZE) {
      const batchIds = toTranslate.slice(i, i + BATCH_SIZE);
      const entries = batchIds.map((id) => [id, enFlat[id]]);
      const translations = await translateBatch(
        entries,
        TARGET_LOCALES[locale]
      );
      for (const id of batchIds) {
        if (translations[id] == null) {
          console.warn(`  [${locale}] missing translation for "${id}", keeping English.`);
          existing[id] = enFlat[id];
        } else {
          existing[id] = translations[id];
        }
        manifestForLocale[id] = enFlat[id];
      }
      console.log(`  [${locale}] ${Math.min(i + BATCH_SIZE, toTranslate.length)}/${toTranslate.length}`);
    }

    writeJsonSorted(localePath, existing);
    manifest[locale] = manifestForLocale;
    console.log(`[${locale}] wrote ${localePath}.`);
  }

  if (!CHECK_ONLY) {
    writeJsonSorted(MANIFEST_PATH, manifest);
  }

  if (CHECK_ONLY && drift) {
    console.error(
      '\nTranslation catalogs are out of date. Run "npm run i18n:translate" and commit the result.'
    );
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
