import { ComponentAddCommand } from './ComponentAddCommand.js';
import { ComponentRemoveCommand } from './ComponentRemoveCommand.js';
import { EntityCloneCommand } from './EntityCloneCommand.js';
import { EntityCreateCommand } from './EntityCreateCommand.js';
import { EntityPasteCommand } from './EntityPasteCommand.js';
import { EntityRemoveCommand } from './EntityRemoveCommand.js';
import { EntityReparentCommand } from './EntityReparentCommand.js';
import { EntityUpdateCommand } from './EntityUpdateCommand.js';
import { MultiCommand } from './MultiCommand.js';
import { SceneTitleCommand } from './SceneTitleCommand.js';
import { SegmentAddCommand } from './SegmentAddCommand.js';
import { SegmentRemoveCommand } from './SegmentRemoveCommand.js';
import { SegmentUpdateCommand } from './SegmentUpdateCommand.js';
import { StreetReloadCommand } from './StreetReloadCommand.js';

export const commandsByType = new Map();
commandsByType.set('componentadd', ComponentAddCommand);
commandsByType.set('componentremove', ComponentRemoveCommand);
commandsByType.set('entityclone', EntityCloneCommand);
commandsByType.set('entitycreate', EntityCreateCommand);
commandsByType.set('entitypaste', EntityPasteCommand);
commandsByType.set('entityremove', EntityRemoveCommand);
commandsByType.set('entityreparent', EntityReparentCommand);
commandsByType.set('entityupdate', EntityUpdateCommand);
commandsByType.set('multi', MultiCommand);
commandsByType.set('scenetitle', SceneTitleCommand);
commandsByType.set('segmentadd', SegmentAddCommand);
commandsByType.set('segmentremove', SegmentRemoveCommand);
commandsByType.set('segmentupdate', SegmentUpdateCommand);
commandsByType.set('streetreload', StreetReloadCommand);
